# Generated by Django 4.2.10 on 2024-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='logos')),
                ('video', models.FileField(upload_to='videos')),
                ('link', models.CharField(max_length=500)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
